# Generated by Django 2.2.7 on 2019-12-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cep',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='facebook',
            new_name='rg',
        ),
    ]
