# Generated by Django 2.2.7 on 2020-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
    ]
