# Generated by Django 2.2.7 on 2019-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20191119_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='redeSocial',
        ),
        migrations.AddField(
            model_name='paciente',
            name='facebook',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram'),
        ),
    ]
