# Generated by Django 2.2.7 on 2020-01-09 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativar essa Conta ?')),
                ('nomeCompleto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Completo')),
                ('cargo', models.CharField(choices=[('1', 'GERENTE'), ('2', 'ADMINISTRADOR'), ('3', 'CAIXA'), ('4', 'DENTISTA'), ('5', 'ATENDENTE'), ('6', 'MANUTENÇÃO DO SISTEMA')], default='4', max_length=2, null=True, verbose_name='Cargo')),
                ('email', models.CharField(blank=True, help_text='E-mail tutilizado para acessar o sistema', max_length=120, null=True, unique=True, verbose_name='Email de acesso')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de acesso')),
            ],
        ),
    ]
