# Generated by Django 2.2.7 on 2019-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='ativo',
            field=models.BooleanField(default=False, null=True, verbose_name='Ativar essa Conta ?'),
        ),
    ]
