# Generated by Django 2.2.7 on 2019-12-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cargo',
            field=models.CharField(choices=[('1', 'GERENTE'), ('2', 'ADMINISTRADOR'), ('3', 'CAIXA'), ('4', 'DENTISTA'), ('5', 'ATENDENTE'), ('6', 'MANUTENÇÃO DO SISTEMA')], default='4', max_length=2, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='email',
            field=models.CharField(blank=True, help_text='E-mail tutilizado para acessar o sistema', max_length=120, null=True, unique=True, verbose_name='Email de acesso'),
        ),
    ]
