# Generated by Django 2.2.7 on 2019-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0002_auto_20191221_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='permissoes',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
