# Generated by Django 2.2.7 on 2020-01-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('servico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'AGENDADO'), ('2', 'FINALIZADO'), ('3', 'EM ESPERA'), ('4', 'CANCELADO'), ('5', 'EM ATENDIMENTO')], default='1', max_length=2, verbose_name='Status')),
                ('periodo', models.CharField(choices=[('1', 'MANHÃ'), ('2', 'TARDE'), ('3', 'NOITE')], default='1', max_length=2, verbose_name='Período')),
                ('data', models.CharField(max_length=10, null=True, verbose_name='Data')),
                ('hora', models.CharField(max_length=5, null=True, verbose_name='Hora')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Conta', verbose_name='Profissional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente', verbose_name='Paciente')),
                ('servicos', models.ManyToManyField(to='servico.Servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
