# Generated by Django 2.2.7 on 2020-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200110_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('1', 'AGENDADO'), ('2', 'FINALIZADO'), ('3', 'EM ESPERA'), ('4', 'CANCELADO'), ('5', 'EM ATENDIMENTO'), ('6', 'REAGENDADO')], default='1', max_length=2, verbose_name='Status'),
        ),
    ]
