# Generated by Django 2.2.7 on 2019-12-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, null=True, verbose_name='Ativar Servico')),
                ('nome_servico', models.CharField(default=True, max_length=120, null=True, verbose_name='Nome do serviço')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do serviço')),
                ('tempo_servico', models.CharField(default=True, max_length=50, verbose_name='Tempo de Serviço')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
    ]
