# Generated by Django 2.2.7 on 2020-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativar Servico ?')),
                ('nome', models.CharField(default=True, max_length=120, null=True, verbose_name='Nome do serviço')),
                ('tempo', models.CharField(default='0', help_text='Tempo estimado em minutos para realizar o serviço', max_length=4, null=True, verbose_name='Tempo de Serviço')),
                ('valor_total', models.CharField(default='0', help_text='Valor total do serviço', max_length=8, null=True, verbose_name='Valor total')),
                ('valor_clinica', models.CharField(default='0', help_text='Valor de lucro da clínica', max_length=8, null=True, verbose_name='Valor clínica')),
                ('valor_mao_obra', models.CharField(default='0', help_text='Valor de custo do profissional para realizar o serviço', max_length=8, null=True, verbose_name='Valor da mão de obra')),
                ('valor_produtos', models.CharField(default='0', help_text='Soma de cada produto', max_length=8, null=True, verbose_name='Soma dos produtos')),
                ('produtos', models.ManyToManyField(blank=True, help_text='Produtos selecionados para realizar o serviço', to='produto.Produto')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
    ]
