# Generated by Django 2.2.7 on 2019-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191220_1428'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto_servico',
            field=models.ManyToManyField(null=True, to='produto.Produto', verbose_name='Produtos'),
        ),
    ]
