# Generated by Django 2.2.7 on 2019-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_servico_produto_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='produto_servico',
            field=models.ManyToManyField(to='produto.Produto', verbose_name='Produtos'),
        ),
    ]
