# Generated by Django 2.2.7 on 2019-12-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191220_1428'),
        ('servico', '0003_auto_20191226_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome_servico',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='produto_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tempo_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_servico',
        ),
        migrations.AddField(
            model_name='servico',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='Produtos selecionados para realizar o serviço', to='produto.Produto'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tempo',
            field=models.CharField(default='0', help_text='Tempo estimado em minutos para realizar o serviço', max_length=4, null=True, verbose_name='Tempo de Serviço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_clinica',
            field=models.CharField(default='0', help_text='Valor de lucro da clínica', max_length=4, null=True, verbose_name='Valor clínica'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_mao_obra',
            field=models.CharField(default='0', help_text='Valor de custo do profissional para realizar o serviço', max_length=4, null=True, verbose_name='Valor da mão de obra'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_produtos',
            field=models.CharField(default='0', help_text='Soma de cada produto', max_length=4, null=True, verbose_name='Soma dos produtos'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_total',
            field=models.CharField(default='0', help_text='Valor total do serviço', max_length=4, null=True, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativar Servico ?'),
        ),
    ]
