# Generated by Django 2.2.7 on 2020-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativar Produto ?')),
                ('nome', models.CharField(max_length=120, null=True, verbose_name='Nome do produto')),
                ('tipo', models.CharField(choices=[('UN', 'Unidade'), ('LT', 'litro'), ('CX', 'Caixa'), ('M', 'Metro')], default='UN', max_length=3, null=True, verbose_name='Unidade da Medida')),
                ('valor', models.CharField(default='0', max_length=8, null=True, verbose_name='Valor do produto')),
                ('quantidade', models.CharField(default='1', max_length=4, null=True, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
