# Generated by Django 2.2.7 on 2019-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, null=True, verbose_name='Ativar Produto ?')),
                ('nome_produto', models.CharField(default=True, max_length=120, null=True, verbose_name='Nome do produto')),
                ('valor_produto', models.BooleanField(default=True, null=True, verbose_name='Valor do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
