# Generated by Django 2.2.7 on 2019-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(default=True, max_length=20, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
