# Generated by Django 2.2.7 on 2019-12-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20191220_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('UN', 'UN'), ('LT', 'LT'), ('CX', 'CX'), ('M', 'M')], default='UN', max_length=20, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
