# Generated by Django 2.2.7 on 2019-12-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191220_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=120, null=True, verbose_name='Nome do produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(default='1', max_length=5, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('UN', 'Unidade'), ('LT', 'litro'), ('CX', 'Caixa'), ('M', 'Metro')], default='UN', max_length=3, null=True, verbose_name='Unidade da Medida'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.CharField(default='0', max_length=4, null=True, verbose_name='Valor do produto'),
        ),
    ]
