# Generated by Django 2.2.7 on 2019-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20191227_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(default='1', max_length=6, null=True, verbose_name='Quantidade'),
        ),
    ]
