# Generated by Django 2.2.7 on 2019-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20191227_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(default='1', max_length=10, null=True, verbose_name='Quantidade'),
        ),
    ]
