# Generated by Django 2.2.9 on 2020-01-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=True, max_length=120, null=True, verbose_name='Descrição da Despesa')),
                ('categoria', models.CharField(default=True, max_length=120, null=True, verbose_name='Categoria da Despesa')),
                ('data_vencimento', models.CharField(max_length=10, null=True, verbose_name='Data do Vencimento')),
                ('valor', models.CharField(default='0', help_text='Valor da Despesa', max_length=8, null=True, verbose_name='Valor da Despesa')),
                ('data_pagamento', models.CharField(max_length=10, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('1', 'DINHEIRO'), ('2', 'DEBITO'), ('3', 'CREDITO'), ('4', 'BOLETO'), ('5', 'CHEQUE')], default='1', help_text='Escolha a forma de pagamento', max_length=2, verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
