# Generated by Django 2.2.9 on 2020-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=True, max_length=120, null=True, verbose_name='Descrição da categoria')),
                ('observacao', models.CharField(default=True, max_length=120, null=True, verbose_name='Obsercao da categoria')),
            ],
        ),
    ]
