# Generated by Django 2.2.9 on 2020-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20200114_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='forma_pagamento',
            field=models.CharField(choices=[('1', 'DINHEIRO'), ('2', 'DEBITO'), ('3', 'CREDITO')], default=1, max_length=8, verbose_name='Forma de Pagamento'),
        ),
    ]
