# Generated by Django 2.2.9 on 2020-02-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20200205_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], default=1, help_text='Escolha a forma de pagamento', max_length=8, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], default=1, max_length=8, verbose_name='Forma de Pagamento'),
        ),
    ]
