# Generated by Django 2.2.9 on 2020-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_categoria_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativar Despesa ?'),
        ),
        migrations.AddField(
            model_name='receita',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativar Receita ?'),
        ),
    ]
